# Generated by Django 3.0.3 on 2021-07-16 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_logement_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='logement',
        ),
        migrations.RemoveField(
            model_name='logement',
            name='category',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='logement',
        ),
        migrations.AddField(
            model_name='announce',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='announce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Announce'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='announce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Announce'),
            preserve_default=False,
        ),
    ]
