# Generated by Django 3.0.3 on 2021-07-18 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210716_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date_of_visit',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='effectivity_of_meet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='manager_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manager_visit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visit',
            name='validation_of_meet',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.ImageField(upload_to='photos/')),
                ('p2', models.ImageField(upload_to='photos/')),
                ('p3', models.ImageField(upload_to='photos/')),
                ('p4', models.ImageField(upload_to='photos/')),
                ('p5', models.ImageField(upload_to='photos/')),
                ('p6', models.ImageField(upload_to='photos/')),
                ('announce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Announce')),
            ],
        ),
    ]
