# Generated by Django 3.0.3 on 2021-07-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210718_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
