# Generated by Django 3.0.3 on 2021-07-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_announce_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
    ]
