# Generated by Django 3.0.3 on 2021-07-19 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210719_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announce',
            name='bailleur',
        ),
        migrations.AddField(
            model_name='announce',
            name='proprietaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proprietaire', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
