# Generated by Django 3.0.3 on 2021-07-20 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comment_author_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('announce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Announce')),
            ],
        ),
    ]
