# Generated by Django 3.0.3 on 2021-07-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_view'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='View',
            new_name='Views_announce',
        ),
    ]
