# Generated by Django 3.0.3 on 2021-07-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210720_0712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
