# Generated by Django 3.0.3 on 2021-07-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='number_of_views',
            field=models.IntegerField(default=0),
        ),
    ]
